### PR TITLE
Fix integer overflow parsing

### LINKED ISSUE #134: [PE-D] Integer overflow error for indexes above max value of integer for java
If the index is above the max value for an integer for java, the command reply is that there is no index, when an index was provided.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: SKCheongBrian/ped#1

### PR DESCRIPTION
**Pull request by itzblim**
Resolves #134, #135, #166

Let's:
- Introduce a hard limit on indices specified by the user (1 <= index <= 1,000,000)
- Update the user guide and tests accordingly

### CODE REVIEW

**Comment by itzblim** [comment]
Forgot to add tests but I don't have my laptop w me rn. Will reopen later

**Comment by itzblim** [comment]
Added tests and updated private methods.

**Review by luminousleek — APPROVED** [review]
lgtm! thanks blim!

**Comment by bentanjunrong** [comment]
Thank you for the hard work sir!

**Pull request merged**
